title: 'Freunde von Gods Golden Acre Deutschland e. V.'
displayTitle: 'Freunde von Gods Golden Acre'
keywords: GGA, FOGGADE, Verein, gemeinn√ºtzig
taxonomies: [category,tag]                  # Arbitrary list of taxonomy types
author:
  name: Samuel Stein
  email: 'mail@samuelstein.de'
metadata:
    description: 'Freunde von Gods Golden Acre Deutschland e. V.'

